### PR TITLE
Fix parsing XML split across packets

### PR DESCRIPTION
**Pull request by hellosmithy**
Fixes https://github.com/rafaeljesus/koa-xml/issues/1

### CODE REVIEW

**Comment by rafaeljesus** [comment]
@hellosmithy LGTM

**Comment by hellosmithy** [comment]
@rafaeljesus thanks for the quick response. Any chance we could get this onto npm?

**Comment by rafaeljesus** [comment]
Yup sure, just running specs and publishing in a few minutes

**Comment by rafaeljesus** [comment]
@hellosmithy released `+ koa-xml@1.0.2`

**Pull request merged**
